"""Asset generation for creative projects: sound effects (ORPHEUS / AudioGen), voice lines (HERMES / Kokoro), game sprites
with transparent backgrounds and seamless textures (NYX / FLUX + BiRefNet). Every tool saves into the Studio project when
there is one (assets/audio/…, assets/sprites/…, assets/textures/…) and into /api/files otherwise. Registered into
tools.TOOLS by register(); generate_music and generate_image live in tools.py and use save_output from here."""
import asyncio
import io
import os
import random
import re
import time
import uuid

import httpx
import numpy as np

import db
from tools import COMFY, FILES, ORPHEUS, TOOLS, ToolResult, _comfy_run, _flux_workflow, _fn, _snap, make_room, BIREFNET

HERMES = os.environ.get("SHELLB_HERMES", "http://localhost:8001")
STABLE_AUDIO = os.environ.get("SHELLB_STABLE_AUDIO", "http://127.0.0.1:8003")


async def _stable_audio_up() -> bool:
    try:
        async with httpx.AsyncClient(timeout=2) as c:
            return (await c.get(f"{STABLE_AUDIO}/health")).status_code == 200
    except httpx.HTTPError:
        return False


def slug(text: str, fallback: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower())[:40].strip("-") or fallback


async def save_output(ctx, data: bytes, default_rel: str, ext: str, save_as: str = "") -> tuple[str | None, str]:
    """Write generated bytes into the project (returns its relative path and raw URL) or into /api/files.
    Raises ValueError when save_as escapes the project."""
    if ctx.project_id:
        root = (db.DATA / "projects" / ctx.project_id).resolve()
        want = (save_as or "").strip().lstrip("/") or default_rel
        want = re.sub(r"\.\w+$", "", want) + ext
        dest = (root / want).resolve()
        if not str(dest).startswith(str(root) + "/"):
            raise ValueError(f"save_as must stay inside the project: {want!r}")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        await ctx.emit({"type": "file", "path": want, "action": "created"})
        return want, f"/api/projects/{ctx.project_id}/raw/{want}"
    name = f"{default_rel.rsplit('/', 1)[-1].rsplit('.', 1)[0]}-{uuid.uuid4().hex[:8]}{ext}"
    (FILES / name).write_bytes(data)
    return None, f"/api/files/{name}"


# ── audio post-processing (numpy + soundfile) ───────────────────────────────

def _read(wav: bytes):
    import soundfile as sf
    data, sr = sf.read(io.BytesIO(wav), dtype="float32", always_2d=True)
    return data, sr


def _write(data: np.ndarray, sr: int, normalize: bool = False) -> bytes:
    import soundfile as sf
    peak = float(np.abs(data).max()) if data.size else 0
    if peak > 0.891 or (normalize and peak > 1e-4):  # -1 dBFS
        data = data * (0.891 / peak)
    buf = io.BytesIO()
    sf.write(buf, data, sr, format="WAV", subtype="PCM_16")
    return buf.getvalue()


def trim_and_fade(wav: bytes, fade_ms: float = 8, thresh_db: float = -45) -> bytes:
    """Trim leading/trailing near-silence (one-shot SFX should start on the transient) and add tiny fades against clicks."""
    data, sr = _read(wav)
    env = np.abs(data).max(axis=1)
    thresh = 10 ** (thresh_db / 20) * max(float(env.max()), 1e-9)
    loud = np.nonzero(env > thresh)[0]
    if loud.size:
        start = max(0, loud[0] - int(sr * 0.005))
        end = min(len(data), loud[-1] + int(sr * 0.05))
        data = data[start:end]
    n = min(int(sr * fade_ms / 1000), len(data) // 4)
    if n > 1:
        ramp = np.linspace(0, 1, n, dtype=np.float32)[:, None]
        data[:n] *= ramp
        data[-n:] *= ramp[::-1]
    return _write(data, sr, normalize=True)  # consistent levels across a sound set


def make_loop(wav: bytes, xfade_s: float = 1.0) -> bytes:
    """Crossfade the tail into the head (equal power) so the clip loops without a seam."""
    data, sr = _read(wav)
    n = min(int(sr * xfade_s), len(data) // 3)
    if n < 16:
        return wav
    t = np.linspace(0, np.pi / 2, n, dtype=np.float32)[:, None]
    head, tail = data[:n], data[-n:]
    blended = tail * np.cos(t) + head * np.sin(t)
    out = np.concatenate([blended, data[n:-n]])
    return _write(out, sr, normalize=True)


def _duration(wav: bytes) -> float:
    data, sr = _read(wav)
    return len(data) / sr


# ── sound effects ───────────────────────────────────────────────────────────

async def generate_sfx(args, ctx):
    prompt = str(args.get("prompt") or "").strip()
    if not prompt:
        return ToolResult("Describe the sound: source, action, material, space, e.g. 'heavy wooden door slams in a stone hall'.",
                          error=True)
    loop = bool(args.get("loop"))
    want = str(args.get("engine") or "auto").lower()
    stable = want in ("auto", "stable", "stable-audio") and await _stable_audio_up()
    fell_back = want in ("stable", "stable-audio") and not stable
    duration = max(0.5, min(46.0 if stable else 30.0, float(args.get("duration") or 3)))
    variations = max(1, min(4, int(args.get("variations") or 1)))
    evicted = await make_room(14 if stable else 10, {ctx.agent.get("model", "")})
    results, urls, saved = [], [], []
    base = slug(prompt, "sfx")
    t0 = time.time()
    async with httpx.AsyncClient(timeout=600) as c:
        for i in range(variations):
            if stable:
                r = await c.post(f"{STABLE_AUDIO}/generate", json={"prompt": prompt, "duration": duration + (1.0 if loop else 0)})
            else:
                r = await c.post(f"{ORPHEUS}/generate/sfx", json={"prompt": prompt, "duration": duration + (1.0 if loop else 0)})
            if r.status_code >= 400:
                return ToolResult(f"{'Stable Audio' if stable else 'ORPHEUS'} failed: {r.text[:500]}", error=True)
            wav = make_loop(r.content) if loop else trim_and_fade(r.content)
            sub = "ambience" if loop else "sfx"
            suffix = f"-{i + 1}" if variations > 1 else ""
            save_as = str(args.get("save_as") or "")
            if save_as and variations > 1:
                save_as = re.sub(r"(\.\w+)?$", f"{suffix}.wav", save_as, count=1)
            try:
                rel, url = await save_output(ctx, wav, f"assets/audio/{sub}/{base}{suffix}.wav", ".wav", save_as)
            except ValueError as e:
                return ToolResult(str(e), error=True)
            urls.append(url)
            results.append(f"{rel or url} ({_duration(wav):.2f}s)")
            if rel:
                saved.append(rel)
    if stable:  # hand its ~6 GB back to the language models
        async with httpx.AsyncClient(timeout=30) as c:
            try:
                await c.post(f"{STABLE_AUDIO}/unload")
            except httpx.HTTPError:
                pass
    note = f" (evicted idle models to make room: {', '.join(evicted)})" if evicted else ""
    if fell_back:
        note += " (Stable Audio is not running, so this used AudioGen.)"
    engine = "Stable Audio Open (44.1 kHz stereo)" if stable else "AudioGen (16 kHz mono)"
    model = "stabilityai/stable-audio-open-1.0" if stable else "facebook/audiogen-medium"
    how = ("Seamless loop: play it with loop=true (an <audio loop> element, or WebAudio with source.loop = true). "
           if loop else "Trimmed to start on the sound, with tiny fades. ")
    return ToolResult(f"Generated {variations} sound effect(s) with {engine} in {time.time() - t0:.0f}s: "
                      f"{', '.join(results)}. {how}Players are shown to the user; don't link them. For games, preload each "
                      "file once with fetch + AudioContext.decodeAudioData and play it through a shared gain node (mute "
                      "toggle), detuning it slightly per play (playbackRate 0.95-1.05) so repeats don't sound robotic. "
                      "Listen-test isn't possible for you: tell the user which sounds to audition." + note,
                      {"audio": urls, "prompt": prompt, "audioInfo": {"model": model, "prompt": prompt}})


# ── voice lines ─────────────────────────────────────────────────────────────

VOICE_HINT = ("Kokoro voices: af_heart, af_bella, af_nicole, af_sarah, af_sky (US female); am_adam, am_michael, am_fenrir, "
              "am_puck (US male); bf_emma, bf_isabella, bf_alice, bf_lily (UK female); bm_george, bm_lewis, bm_daniel, "
              "bm_fable (UK male).")


async def generate_voice(args, ctx):
    lines = args.get("lines")
    if not lines:
        text = str(args.get("text") or "").strip()
        if not text:
            return ToolResult("Give text (one line) or lines (a list of {id, text, voice}).", error=True)
        lines = [{"id": args.get("save_as") or slug(text, "line"), "text": text, "voice": args.get("voice")}]
    if not isinstance(lines, list) or len(lines) > 40:
        return ToolResult("lines must be a list of at most 40 {id, text, voice} objects.", error=True)
    speed = max(0.5, min(2.0, float(args.get("speed") or 1.0)))
    urls, results = [], []
    async with httpx.AsyncClient(timeout=180) as c:
        for ln in lines:
            if not isinstance(ln, dict) or not str(ln.get("text") or "").strip():
                continue
            voice = str(ln.get("voice") or args.get("voice") or "af_heart")
            r = await c.post(f"{HERMES}/tts", json={"text": str(ln["text"]), "voice": voice,
                                                    "speed": float(ln.get("speed") or speed), "format": "wav"})
            if r.status_code >= 400:
                return ToolResult(f"HERMES failed on {ln.get('id')!r}: {r.text[:300]}", error=True)
            wav = trim_and_fade(r.content, fade_ms=5, thresh_db=-50)
            ident = str(ln.get("id") or slug(str(ln["text"]), "line"))
            explicit = ident if "/" in ident else ""
            try:
                rel, url = await save_output(ctx, wav, f"assets/audio/voice/{slug(ident, 'line')}.wav", ".wav", explicit)
            except ValueError as e:
                return ToolResult(str(e), error=True)
            urls.append(url)
            results.append(f"{rel or url} [{voice}, {_duration(wav):.1f}s]")
    if not urls:
        return ToolResult("No lines had text.", error=True)
    return ToolResult(f"Synthesized {len(urls)} voice line(s) with Kokoro (24 kHz): {'; '.join(results)}. Players are shown to "
                      "the user. Kokoro reads plain text: spell out numbers and acronyms the way they should be spoken, "
                      "and use punctuation for pacing. " + VOICE_HINT,
                      {"audio": urls[:12], "prompt": "; ".join(str(ln.get("text"))[:60] for ln in lines[:3])})


# ── sprites (FLUX → BiRefNet cut-out → trimmed RGBA) ────────────────────────

SPRITE_STYLE = (", a single isolated game asset, the entire subject in frame and centered with margin around it, on a plain "
                "flat solid {bg} background, no ground, no cast shadow, no text, no border")


def _cutout(rgb: bytes, mask: bytes, size: int | None, pixel: int | None, colors: int | None) -> tuple[bytes, tuple]:
    from PIL import Image
    im = Image.open(io.BytesIO(rgb)).convert("RGB")
    m = Image.open(io.BytesIO(mask)).convert("L").resize(im.size)
    rgba = im.copy()
    rgba.putalpha(m)
    box = m.point(lambda v: 255 if v > 24 else 0).getbbox()
    if box:
        pad = max(4, (box[2] - box[0] + box[3] - box[1]) // 40)
        box = (max(0, box[0] - pad), max(0, box[1] - pad), min(im.width, box[2] + pad), min(im.height, box[3] + pad))
        rgba = rgba.crop(box)
    if pixel:  # pixel art: shrink to the grid with a box filter, harden alpha, cut the palette
        w, h = rgba.size
        scale = pixel / max(w, h)
        small = rgba.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.BOX)
        a = small.split()[3].point(lambda v: 255 if v >= 128 else 0)
        rgb_small = small.convert("RGB").quantize(colors=colors or 16, method=Image.Quantize.MEDIANCUT).convert("RGB")
        small = rgb_small.copy()
        small.putalpha(a)
        rgba = small
    elif size:
        rgba.thumbnail((size, size), Image.LANCZOS)
    out = io.BytesIO()
    rgba.save(out, "PNG", optimize=True)
    return out.getvalue(), rgba.size


def _checker_preview(png: bytes, scale_to: int = 512) -> bytes:
    """The sprite over a checkerboard, upscaled nearest-neighbour, so a vision model can judge the cut-out."""
    from PIL import Image
    im = Image.open(io.BytesIO(png)).convert("RGBA")
    k = max(1, scale_to // max(im.size))
    im = im.resize((im.width * k, im.height * k), Image.NEAREST)
    bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
    cell = max(8, im.width // 16)
    px = bg.load()
    for y in range(im.height):
        for x in range(im.width):
            if (x // cell + y // cell) % 2:
                px[x, y] = (204, 204, 204, 255)
    bg.alpha_composite(im)
    out = io.BytesIO()
    bg.convert("RGB").save(out, "PNG")
    return out.getvalue()


async def _flux_png(c, prompt, width, height, seed, extra: dict | None = None, quality: str = "draft") -> dict:
    wf = _flux_workflow(prompt, width, height, seed, quality)
    if extra:
        wf.update(extra)
    outputs = await _comfy_run(c, wf, 600)

    async def fetch(item):
        return (await c.get(f"{COMFY}/view", params={"filename": item["filename"], "subfolder": item.get("subfolder", ""),
                                                     "type": item.get("type", "output")})).content
    return {k: await fetch(v["images"][0]) for k, v in outputs.items() if v.get("images")}


async def generate_sprite(args, ctx):
    prompt = str(args.get("prompt") or "").strip()
    if not prompt:
        return ToolResult("Describe the sprite: subject, pose/view (side view, top-down, 3/4), art style, palette.", error=True)
    pixel = int(args.get("pixel_size") or 0) or None
    if pixel:
        pixel = max(8, min(256, pixel))
    size = max(16, min(1024, int(args.get("size") or 256)))
    colors = max(2, min(64, int(args.get("colors") or 16))) if pixel else None
    bg = "white" if args.get("background") != "black" else "black"
    seed = int(args.get("seed") or random.randint(0, 2**31 - 1))
    style = " pixel art, crisp hard edges, limited palette," if pixel else ""
    evicted = await make_room(30, {ctx.agent.get("model", "")})
    extra = {
        "30": {"class_type": "LoadBackgroundRemovalModel", "inputs": {"bg_removal_name": BIREFNET}},
        "31": {"class_type": "RemoveBackground", "inputs": {"image": ["9", 0], "bg_removal_model": ["30", 0]}},
        "32": {"class_type": "MaskToImage", "inputs": {"mask": ["31", 0]}},
        "33": {"class_type": "SaveImage", "inputs": {"filename_prefix": "ShellB_Web_mask", "images": ["32", 0]}},
    }
    t0 = time.time()
    async with httpx.AsyncClient(timeout=60) as c:
        try:
            imgs = await _flux_png(c, prompt + "," + style + SPRITE_STYLE.format(bg=bg), 1024, 1024, seed, extra,
                                   str(args.get("quality") or "draft"))
        except (RuntimeError, TimeoutError) as e:
            return ToolResult(str(e), error=True)
        finally:
            await c.post(f"{COMFY}/free", json={"unload_models": True, "free_memory": True})
    if "10" not in imgs or "33" not in imgs:
        return ToolResult("ComfyUI finished without the image or its mask.", error=True)
    png, dims = await asyncio.to_thread(_cutout, imgs["10"], imgs["33"], size, pixel, colors)
    try:
        rel, url = await save_output(ctx, png, f"assets/sprites/{slug(prompt, 'sprite')}-{seed % 10000}.png", ".png",
                                     str(args.get("save_as") or ""))
    except ValueError as e:
        return ToolResult(str(e), error=True)
    preview = await asyncio.to_thread(_checker_preview, png)
    from studio_tools import _deliver_images
    review, model_imgs = await _deliver_images(ctx, [preview], "", "This is a generated game sprite with a transparent "
                                               f"background, shown over a checkerboard. Brief: {prompt}. Is the subject "
                                               "complete and cleanly cut out? List defects: missing parts, leftover "
                                               "background, halos, cropped edges, wrong view or style.")
    note = f" (evicted idle models: {', '.join(evicted)})" if evicted else ""
    kind = f"{pixel}px pixel-art grid, {colors} colors (draw it with imageSmoothingEnabled = false and CSS image-rendering: pixelated)" \
        if pixel else "anti-aliased"
    return ToolResult(f"Generated a transparent sprite {dims[0]}×{dims[1]} ({kind}) in {time.time() - t0:.0f}s, seed {seed}: "
                      f"{rel or url}. It is trimmed to the subject. For animation frames, reuse the seed and change only the "
                      "pose words, then pack frames into a sheet with run_code (PIL) and keep the frame size constant. "
                      "For a consistent set, keep the same style words in every prompt." + note + review,
                      {"images": [url], "prompt": prompt}, model_images=model_imgs)


# ── seamless textures (FLUX → offset cross-blend) + normal map ─────────────

TEXTURE_STYLE = (", seamless tileable texture, flat orthographic top-down view of the surface filling the entire frame, "
                 "even diffuse lighting, no shadows, no perspective, no vignette, no objects, no text")


def _seamless(png: bytes, size: int) -> bytes:
    """Blend the image with its half-offset copy: the copy's borders already wrap, and a radial weight hides its
    centre seam under the original. Then resize."""
    from PIL import Image
    im = np.asarray(Image.open(io.BytesIO(png)).convert("RGB"), dtype=np.float32)
    h, w = im.shape[:2]
    rolled = np.roll(im, (h // 2, w // 2), axis=(0, 1))
    y = np.abs(np.linspace(-1, 1, h))[:, None]
    x = np.abs(np.linspace(-1, 1, w))[None, :]
    d = np.maximum(x, y)  # 0 at centre, 1 at the border
    wgt = np.clip((0.92 - d) / 0.45, 0, 1) ** 1.5
    wgt = wgt[..., None]
    out = im * wgt + rolled * (1 - wgt)
    img = Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))
    if size != w:
        img = img.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def _normal_map(png: bytes, strength: float = 2.0) -> bytes:
    from PIL import Image
    g = np.asarray(Image.open(io.BytesIO(png)).convert("L"), dtype=np.float32) / 255
    dx = (np.roll(g, -1, 1) - np.roll(g, 1, 1)) * strength  # wraps, so the normal map tiles too
    dy = (np.roll(g, -1, 0) - np.roll(g, 1, 0)) * strength
    n = np.dstack([-dx, -dy, np.ones_like(g)])
    n /= np.linalg.norm(n, axis=2, keepdims=True)
    buf = io.BytesIO()
    Image.fromarray(((n * 0.5 + 0.5) * 255).astype(np.uint8)).save(buf, "PNG", optimize=True)
    return buf.getvalue()


def _tile_preview(png: bytes) -> bytes:
    from PIL import Image
    im = Image.open(io.BytesIO(png)).convert("RGB")
    im.thumbnail((256, 256))
    sheet = Image.new("RGB", (im.width * 2, im.height * 2))
    for i in range(2):
        for j in range(2):
            sheet.paste(im, (i * im.width, j * im.height))
    buf = io.BytesIO()
    sheet.save(buf, "PNG")
    return buf.getvalue()


async def generate_texture(args, ctx):
    prompt = str(args.get("prompt") or "").strip()
    if not prompt:
        return ToolResult("Describe the surface: material, scale, wear, color, e.g. 'mossy cobblestone, small stones'.", error=True)
    size = _snap(args.get("size") or 1024, 256, 1024)
    seed = int(args.get("seed") or random.randint(0, 2**31 - 1))
    evicted = await make_room(28, {ctx.agent.get("model", "")})
    t0 = time.time()
    async with httpx.AsyncClient(timeout=60) as c:
        try:
            imgs = await _flux_png(c, prompt + TEXTURE_STYLE, 1024, 1024, seed, quality=str(args.get("quality") or "draft"))
        except (RuntimeError, TimeoutError) as e:
            return ToolResult(str(e), error=True)
        finally:
            await c.post(f"{COMFY}/free", json={"unload_models": True, "free_memory": True})
    if "10" not in imgs:
        return ToolResult("ComfyUI finished without an image.", error=True)
    tex = await asyncio.to_thread(_seamless, imgs["10"], size)
    base = f"assets/textures/{slug(prompt, 'texture')}-{seed % 10000}.png"
    save_as = str(args.get("save_as") or "")
    try:
        rel, url = await save_output(ctx, tex, base, ".png", save_as)
        files, urls = [rel or url], [url]
        if args.get("normal_map", True):
            nrel, nurl = await save_output(ctx, await asyncio.to_thread(_normal_map, tex),
                                           (rel or base)[:-4] + "-normal.png", ".png", ((rel or base)[:-4] + "-normal.png") if rel else "")
            files.append(nrel or nurl)
            urls.append(nurl)
    except ValueError as e:
        return ToolResult(str(e), error=True)
    from studio_tools import _deliver_images
    review, model_imgs = await _deliver_images(ctx, [await asyncio.to_thread(_tile_preview, tex)], "",
                                               f"This is a texture tiled 2×2 to check that it is seamless. Brief: {prompt}. "
                                               "Are seams, repeated blotches, ghosting or perspective visible?")
    note = f" (evicted idle models: {', '.join(evicted)})" if evicted else ""
    return ToolResult(f"Generated a seamless {size}×{size} texture in {time.time() - t0:.0f}s, seed {seed}: {', '.join(files)}. "
                      "CSS: background-image with background-size for the tile size. three.js: texture.wrapS = wrapT = "
                      "RepeatWrapping, colorSpace = SRGBColorSpace for color (not for the normal map), set repeat. "
                      "The normal map is derived from brightness, so it is approximate." + note + review,
                      {"images": urls, "prompt": prompt}, model_images=model_imgs)


# ── registry ────────────────────────────────────────────────────────────────

def register():
    TOOLS["generate_sfx"] = {
        "fn": generate_sfx, "service": "orpheus",
        "ui": {"displayName": "Sound Effects", "icon": "AudioLines", "category": "creative",
               "description": "Text to sound effects, ambience and loops: Stable Audio Open (44.1 kHz stereo), AudioGen fallback."},
        "schema": _fn("generate_sfx", "Generate sound effects or ambience from a text description (AudioGen). Describe the "
                      "source, action, material and space: 'coins clinking into a leather pouch', 'laser blaster shot, sci-fi, "
                      "short', 'rain on a tin roof'. Not for music (use generate_music) or speech (generate_voice).",
                      {"prompt": {"type": "string"},
                       "duration": {"type": "number", "description": "Seconds, 0.5-46 (default 3; AudioGen max 30). One-shots are trimmed to the sound."},
                       "engine": {"type": "string", "enum": ["auto", "stable", "audiogen"],
                                  "description": "auto (default) = Stable Audio Open when it is running: 44.1 kHz stereo, richer, "
                                                 "also does beats/loops/foley, ~10-30 s per take. audiogen = faster, 16 kHz mono."},
                       "loop": {"type": "boolean", "description": "Make a seamless loop (ambience, engine hum, rain)"},
                       "variations": {"type": "integer", "description": "1-4 takes of the same sound, for random variation in games"},
                       "save_as": {"type": "string", "description": "Studio projects only, e.g. assets/audio/sfx/jump.wav"}},
                      ["prompt"]),
    }
    TOOLS["generate_voice"] = {
        "fn": generate_voice, "service": "hermes",
        "ui": {"displayName": "Voice Lines", "icon": "Mic", "category": "creative",
               "description": "Text to speech for narration, dialogue and UI voice with Kokoro on HERMES."},
        "schema": _fn("generate_voice", "Synthesize spoken voice lines: narration, character dialogue, tutorial voice-over, "
                      "announcer calls. Give one text, or a batch of lines. " + VOICE_HINT,
                      {"text": {"type": "string", "description": "One line to speak"},
                       "voice": {"type": "string", "description": "Kokoro voice id (default af_heart)"},
                       "speed": {"type": "number", "description": "0.5-2.0 (default 1.0)"},
                       "lines": {"type": "array", "description": "Batch: [{id, text, voice?, speed?}]; id becomes the file "
                                 "name in assets/audio/voice/ (or a full path)",
                                 "items": {"type": "object", "properties": {"id": {"type": "string"}, "text": {"type": "string"},
                                                                            "voice": {"type": "string"}, "speed": {"type": "number"}}}},
                       "save_as": {"type": "string", "description": "Single line only: where to save it"}},
                      []),
    }
    TOOLS["generate_sprite"] = {
        "fn": generate_sprite, "service": "nyx",
        "ui": {"displayName": "Sprites", "icon": "Gamepad2", "category": "creative",
               "description": "Game sprites, characters, items and icons with transparent backgrounds (FLUX + BiRefNet)."},
        "schema": _fn("generate_sprite", "Generate one game sprite or cut-out asset (character, enemy, item, prop, pickup, UI "
                      "badge) with a transparent background, trimmed to the subject. Optional pixel-art mode snaps it to a small "
                      "grid with a limited palette. One subject per call.",
                      {"prompt": {"type": "string", "description": "Subject, view (side view / top-down / 3/4 / front), pose, style, palette"},
                       "size": {"type": "integer", "description": "Longest side in px for smooth art, 16-1024 (default 256)"},
                       "pixel_size": {"type": "integer", "description": "Pixel art: longest side on the pixel grid, e.g. 16, 32, 64"},
                       "colors": {"type": "integer", "description": "Pixel art palette size, 2-64 (default 16)"},
                       "background": {"type": "string", "enum": ["white", "black"], "description": "Generation backdrop; black for bright/white subjects"},
                       "quality": {"type": "string", "enum": ["draft", "high"], "description": "high = FLUX.1-dev, slower, better detail"},
                       "seed": {"type": "integer", "description": "Reuse a seed for consistent variations"},
                       "save_as": {"type": "string", "description": "Studio projects only, e.g. assets/sprites/hero-idle.png"}},
                      ["prompt"]),
    }
    TOOLS["generate_texture"] = {
        "fn": generate_texture, "service": "nyx",
        "ui": {"displayName": "Textures", "icon": "Grid3x3", "category": "creative",
               "description": "Seamless tileable textures plus normal maps for games, 3D and web backgrounds."},
        "schema": _fn("generate_texture", "Generate a seamless, tileable surface texture (ground, walls, fabric, wood, metal, "
                      "terrain tiles, web backgrounds) and a matching normal map.",
                      {"prompt": {"type": "string", "description": "Material, scale, wear, color"},
                       "size": {"type": "integer", "description": "Tile size in px, 256-1024 (default 1024)"},
                       "normal_map": {"type": "boolean", "description": "Also write <name>-normal.png (default true)"},
                       "quality": {"type": "string", "enum": ["draft", "high"]},
                       "seed": {"type": "integer"},
                       "save_as": {"type": "string", "description": "Studio projects only, e.g. assets/textures/grass.png"}},
                      ["prompt"]),
    }
